version: "3.8"
services:
  discord:
    image: golang:1.15.7-buster
    command: go run /app/service.discord/main.go
    working_dir: /app
    expose: ["8080", "9090"]
    labels:
    - traefik.http.routers.discord.rule=Host(`discord.localtest.me`)
    - traefik.http.services.discord.loadbalancer.server.port=8080
    - traefik.http.services.discord.loadbalancer.server.scheme=h2c
    depends_on:
    - rp
    volumes:
    - $PWD:/app
  spotify:
    image: golang:1.15.7-buster
    command: go run /app/service.spotify/main.go
    working_dir: /app
    expose: ["8080", "9090"]
    labels:
    - traefik.http.routers.spotify.rule=Host(`spotify.localtest.me`)
    - traefik.http.services.spotify.loadbalancer.server.port=8080
    - traefik.http.services.spotify.loadbalancer.server.scheme=h2c
    depends_on:
    - rp
    volumes:
    - $PWD:/app
  teapot:
    image: golang:1.15.7-buster
    command: go run /app/service.teapot/main.go
    working_dir: /app
    expose: ["8080", "9090"]
    labels:
    - traefik.http.routers.teapot.rule=Host(`teapot.localtest.me`)
    - traefik.http.services.teapot.loadbalancer.server.port=8080
    - traefik.http.services.teapot.loadbalancer.server.scheme=h2c
    depends_on:
    - rp
    volumes:
    - $PWD:/app
  
  rp:
    image: traefik:v2.2
    command:
    - --api.insecure=true
    - --providers.docker=true
    ports:
    - "80:80"
    - "8080:8080"
    volumes:
    # So that Traefik can listen to the Docker events
    - /var/run/docker.sock:/var/run/docker.sock

