// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "euterpe/service.spotify/proto"
)

// SpotifyClient is an autogenerated mock type for the SpotifyClient type
type SpotifyClient struct {
	mock.Mock
}

// GetAuthURL provides a mock function with given fields: ctx, in, opts
func (_m *SpotifyClient) GetAuthURL(ctx context.Context, in *proto.GetAuthURLRequest, opts ...grpc.CallOption) (*proto.GetAuthURLResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.GetAuthURLResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetAuthURLRequest, ...grpc.CallOption) *proto.GetAuthURLResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetAuthURLResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetAuthURLRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListening provides a mock function with given fields: ctx, in, opts
func (_m *SpotifyClient) GetListening(ctx context.Context, in *proto.GetListeningRequest, opts ...grpc.CallOption) (*proto.GetListeningResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.GetListeningResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetListeningRequest, ...grpc.CallOption) *proto.GetListeningResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetListeningResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetListeningRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RedeemCode provides a mock function with given fields: ctx, in, opts
func (_m *SpotifyClient) RedeemCode(ctx context.Context, in *proto.RedeemCodeRequest, opts ...grpc.CallOption) (*proto.RedeemCodeResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.RedeemCodeResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.RedeemCodeRequest, ...grpc.CallOption) *proto.RedeemCodeResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.RedeemCodeResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.RedeemCodeRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
