// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeSpotifyServer is an autogenerated mock type for the UnsafeSpotifyServer type
type UnsafeSpotifyServer struct {
	mock.Mock
}

// mustEmbedUnimplementedSpotifyServer provides a mock function with given fields:
func (_m *UnsafeSpotifyServer) mustEmbedUnimplementedSpotifyServer() {
	_m.Called()
}
