// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	teapotv1pb "euterpe/service.teapot/proto"
)

// TeapotClient is an autogenerated mock type for the TeapotClient type
type TeapotClient struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, in, opts
func (_m *TeapotClient) Create(ctx context.Context, in *teapotv1pb.CreateRequest, opts ...grpc.CallOption) (*teapotv1pb.CreateResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *teapotv1pb.CreateResponse
	if rf, ok := ret.Get(0).(func(context.Context, *teapotv1pb.CreateRequest, ...grpc.CallOption) *teapotv1pb.CreateResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*teapotv1pb.CreateResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *teapotv1pb.CreateRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, in, opts
func (_m *TeapotClient) GetById(ctx context.Context, in *teapotv1pb.GetByIdRequest, opts ...grpc.CallOption) (*teapotv1pb.GetByIdResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *teapotv1pb.GetByIdResponse
	if rf, ok := ret.Get(0).(func(context.Context, *teapotv1pb.GetByIdRequest, ...grpc.CallOption) *teapotv1pb.GetByIdResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*teapotv1pb.GetByIdResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *teapotv1pb.GetByIdRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
