// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeTeapotServer is an autogenerated mock type for the UnsafeTeapotServer type
type UnsafeTeapotServer struct {
	mock.Mock
}

// mustEmbedUnimplementedTeapotServer provides a mock function with given fields:
func (_m *UnsafeTeapotServer) mustEmbedUnimplementedTeapotServer() {
	_m.Called()
}
