// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeEmojiServiceServer is an autogenerated mock type for the UnsafeEmojiServiceServer type
type UnsafeEmojiServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedEmojiServiceServer provides a mock function with given fields:
func (_m *UnsafeEmojiServiceServer) mustEmbedUnimplementedEmojiServiceServer() {
	_m.Called()
}
